package com.darkpixellabs.honeytrap.controller;

import com.darkpixellabs.honeytrap.model.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@RestController @RequestMapping("/api") public class DashboardApiController {
 private final HitRepository repo; public DashboardApiController(HitRepository repo){this.repo=repo;}
 @GetMapping("/stats/summary") public Map<String,Object> summary(){Instant since=Instant.now().minus(24,ChronoUnit.HOURS);List<Object[]>p=repo.mostTargeted(),i=repo.mostActiveIp();Map<String,Object>m=new LinkedHashMap<>();m.put("totalHits",repo.count());m.put("hitsLast24h",repo.countByTimestampAfter(since));m.put("uniqueIps",repo.countDistinctIps(Instant.EPOCH));m.put("mostTargetedEndpoint",p.isEmpty()?null:p.get(0)[1]);m.put("mostActiveIp",i.isEmpty()?null:i.get(0)[1]);return m;}
 @GetMapping("/stats/top-ips") public List<Map<String,Object>> topIps(@RequestParam(defaultValue="10")int limit){return counts(repo.ipCounts(PageRequest.of(0,clamp(limit))),"ip");}
 @GetMapping("/stats/top-paths") public List<Map<String,Object>> topPaths(@RequestParam(defaultValue="10")int limit){return counts(repo.pathCounts(PageRequest.of(0,clamp(limit))),"path");}
 private List<Map<String,Object>>counts(List<Object[]>rows,String key){return rows.stream().map(x->{Map<String,Object>m=new LinkedHashMap<>();m.put(key,x[0]);m.put("hits",x[1]);return m;}).toList();}
 private int clamp(int n){return Math.max(1,Math.min(n,100));}
 @GetMapping("/stats/timeseries") public List<Map<String,Object>> timeseries(@RequestParam(defaultValue="hour")String bucket){if(!bucket.equals("hour")&&!bucket.equals("day"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"bucket must be hour or day");int days=bucket.equals("hour")?7:30;Instant cutoff=Instant.now().minus(days,ChronoUnit.DAYS);Map<String,Long>c=new TreeMap<>();repo.findAllByOrderByTimestampDesc(PageRequest.of(0,50000)).stream().filter(h->h.getTimestamp().isAfter(cutoff)).forEach(h->{ZonedDateTime z=h.getTimestamp().atZone(ZoneOffset.UTC);String k=bucket.equals("hour")?z.truncatedTo(ChronoUnit.HOURS).toString():z.toLocalDate().toString();c.merge(k,1L,Long::sum);});return c.entrySet().stream().map(e->{Map<String,Object>m=new LinkedHashMap<>();m.put("bucket",e.getKey());m.put("hits",e.getValue());return m;}).toList();}
 @GetMapping("/hits") public Page<Hit>hits(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size,@RequestParam(defaultValue="")String ip,@RequestParam(defaultValue="")String path){PageRequest pr=PageRequest.of(Math.max(page,0),Math.max(1,Math.min(size,100)));if(!ip.isBlank()&&!path.isBlank())return repo.findBySourceIpContainingIgnoreCaseAndPathContainingIgnoreCase(ip,path,pr);if(!ip.isBlank())return repo.findBySourceIpContainingIgnoreCase(ip,pr);if(!path.isBlank())return repo.findByPathContainingIgnoreCase(path,pr);return repo.findAllByOrderByTimestampDesc(pr);}
 @GetMapping("/hits/{id}") public Hit hit(@PathVariable long id){return repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"hit not found"));}
}
